### ISSUE TITLE
Creating Map in Carto DB

### ISSUE THREAD

**Issue by aaronsimon** [jueyang/call-me-maybe#10]
Hi Jue,

In Carto DB I'm attempting to create a map of fiber optic internet availability in NYC with the location of tech startups: http://www.digital.nyc/map and https://nycbbmap.com/#/map

I'm having difficulty properly sorting the data in Carto DB. If you are at school today I'd like to meetup. Please let me know.

Thanks,
Aaron

**Comment by jueyang** [comment]
Hi @aaronsimon,

Thanks for posting. I'd like you to do some exploration before we meet (if needed after this).
1. Start with finding the data. You showed me two maps, which are representation of the data. Can you find the raw data that powers the maps?
2. Could you elaborate what you mean by "properly sorting the data"? Maybe post of a screenshot of what you've got in CartoDB? 

Mapping involves a few steps. Let me know which one is tripping you up. Carry on!

**Comment by aaronsimon** [comment]
I attached the internet availability  and tech companies "mapped in NY"
data sets below.

The ultimate question I want to answer: Is there a correlation between
braodband speed and location of tech startups?

We used Carto DB in the last Data Skills class and want to know if it's
possible to combine the two data sets?

Thanks!

**Comment by jueyang** [comment]
Hey @aaronsimon,

I don't see the attachment... GitHub doesn't take email attachments. Could you send me the links where you downloaded them? Or, paste them into gists?

Your goal sounds clear; I think the rest is to understand the specificities of these datasets: how they are structured, which fields can be mapped, if they are formatted correctly, etc. 

Thanks.

**Comment by jueyang** [comment]
@aaronsimon how are you doing on this? If you're set mind if I close this issue?

**Comment by aaronsimon** [comment]
Thanks Jue, go ahead and close the issue.

-Aaron

_Aaron M. Simon_
CUNY Graduate School of Journalism, MA Candidate in Social Journalism
Columbia University Alumnus, BA in Sustainable Development & Human Rights
Phone: 347-981-2748
Twitter: @AaronMSimon (http://twitter.com/aaronmsimon)
LinkedIn: http://www.linkedin.com/in/aaronmsimon

**Comment by jueyang** [comment]
:cool:
