### ISSUE TITLE
Randall's Island field usage data for 2014

### ISSUE THREAD

**Issue by lmechegaray** [jueyang/call-me-maybe#13]
Hi Jue!

I have a new one for you and @amandabee 
I am trying to find field usage data for Randall's Island for 2014.  I want to see how many field permits allocated to private and public schools last year....I searched parks and recreation website but no luck....maybe i am looking in the wrong place?  I also searched open data but i dont think its there........when i looked in there it only had maps of the park and other info i didnt need.

any tips would be great!  Thanks so much!

Luis Miguel Echegaray
social j

**Comment by jueyang** [comment]
Can't emphasize enough that google is your bff. I would start with searching "field permits nyc."

This popped up for me: http://www.nycgovparks.org/parks/randalls-island/facilities/soccer

From there you'd know all the soccer fields available, and you can start search on the permit usage database by Parks and Rec (also popped up when I searched the term): https://www.nycgovparks.org/permits/field-and-court/request

**Comment by lmechegaray** [comment]
perfect.  Thanks!

LME
