### ISSUE TITLE
Weird problem with space and MoJo news quiz (again:/)

### ISSUE THREAD

**Issue by catharob** [jueyang/call-me-maybe#15]
Hey Jue,

This dang newsquiz. I've got it working now (thanks for your help on that!). But I'm having a weird issue that I can't figure out. We're needing to embed a Thinglink hotspotted image for each question, for our quiz about parking. For some reason the quiz is putting in a bunch of extra space below the image and above the questions, which is making it really difficult to read and follow. Here is the live link:
http://digitalstorage.journalism.cuny.edu/catherine.roberts/public_html/parking_quiz/index.html

I've hosted it on digital storage right now, but I can push it to git if that's better for you to check it out. Thanks Jue!

Catherine

**Comment by jueyang** [comment]
Hey @catharob,

If you inspect the elements, you might see that the thinglink images are
embedded as iframes, and the iframes are given a set height, thus the space.

This is probably a css problem. I suggest looking into the style sheet
that's included in the news quiz template.

**Comment by catharob** [comment]
Thanks Jue! It was the iframe size after all. Fixed now!
