### ISSUE TITLE
help with app for coding class!

### ISSUE THREAD

**Issue by catharob** [jueyang/call-me-maybe#19]
Hey Jue, I'm working on our final project for coding, and I'm having trouble appending the data I'm using to the page. My js is here: https://github.com/catharob/app-coding-class/blob/work/js/script.js

I have it organized correctly (in the restaurantArray function) - which Meghan helped my do by nesting _.each functions, so that health code violations are listed under specific restaurants. I can get the restaurant name on the page, and I've tried a similar thing with nesting _.each functions so that the list of complaints will show up under the restaurant name, but it doesn't seem to be working. 

Does that make sense? Probably not. What times will you be around this week? Perhaps I could stop by to get your take! Thanks! - Catherine

**Comment by jueyang** [comment]
These are great bugs! Here's an `script-annotated.js` to help you figure out where things might have gone wrong. https://gist.github.com/jueyang/55bccd2b0e174333b514

However, after trying the above, if you still find yourself scratching your head, come find me! Thursday afternoon after 3pm is good.

PS. if you would like to differentiate `code` from text in a GitHub issue, just add a grave accent ( shift +  ~ ) around the code snippet. So  things like `_.each` or `restaurantArray` will stand out.  (I had no idea it was called the grave accent. Really had to google this one.)

**Comment by catharob** [comment]
Thanks Jue! Your annotations helped! We got our project working and turned
in!

**Comment by jueyang** [comment]
Awesome :)
