### ISSUE TITLE
CartoDB

### ISSUE THREAD

**Issue by MargueriteWard** [jueyang/call-me-maybe#2]
Hey Jue,
 I'm working on CartoDB right now and I'm trying to georeference community districts. I have one table of data that I manually put in and the other data from here http://www.nyc.gov/html/dcp/html/bytes/districts_download_metadata.shtml. Can you help me georeference the community districts? 
Thanks!

**Comment by jueyang** [comment]
It looks like your custom file has a text description of the districts (`Bronx CD 001`) while the boundary files from the site only has an encoded number (`311`). You definitely want the column you're using to join the data to be the same (so `311` is joined with `311`.) It's curious they don't have a file where both the encoded district number and the text district info are present. You might have some luck in the the open data portal. Look for the community district shapefiles : https://nycopendata.socrata.com

If you don't find something that gives you a common column to join on, you can glean some info here: http://www.nyc.gov/html/dcp/html/neigh_info/nhmap.shtml Seems like the first digit of the three-digit district number is a borough number (Manhattan might be 1?) and the rest two correspond to the district numbers.

Also, props to you for being the first person to get in the issue queue and poke me with a very good question! Please poke often. :100: :+1:

**Comment by MargueriteWard** [comment]
thanks!

**Comment by jueyang** [comment]
Gonna close this one. Let me know if you have any questions!
