### ISSUE TITLE
Making embedded Google chart responsive

### ISSUE THREAD

**Issue by tolab** [jueyang/call-me-maybe#25]
Hey,

I have a Google chart [embedded here](http://www.journalism.tolabrennan.com/war-money/). It's occupying half of the page width but I want it to spread across 90% of the page width and also be responsive. I managed to get a static html version of the embedded iframe content (which I could send over to you) and it looks like each rectangle is an svg. It looks like [this](http://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/) might help but help implementing it would be kewl.

I also want to make it skinnier. I tried a find/replace on the height attribute but that didn't work.

Helps!

**Comment by jueyang** [comment]
Hello!

Two questions:
1. Where is the site published?
2. How much html/css do you know?

If your answer to no.1 is wordpress, that means you'll need to add some custom html and css. And whatever your answer is for no.2, this is an excellent opportunity to practice your skills. I won't do the work for you :P but I can walk you through if you bump into some problem.

So. for finer control of svg, you'll change some html (adding classes, etc) once you get it out of the iframe. Then add custom css.

If you keep things in the iframe you can follow [this](http://www.smashingmagazine.com/2014/02/making-embedded-content-work-in-responsive-design/) to make the iframe responsive.

I'm away for the rest of the week and next week, hit me up on slack https://chatwithjue.slack.com/ to chat further.

**Comment by jueyang** [comment]
Let me know if you have other questions.
