### ISSUE TITLE
Understanding My Data

### ISSUE THREAD

**Issue by nlizbethlewis** [jueyang/call-me-maybe#27]
Hi Jue!

I am working on a data viz chart about american work hours. Basically, I started down this road for my pitch and then realized I was thinking about my data all wrong. I don't have a specific tech question about this project, I really just need to talk the data through and think about other ways I might be able to chart this trend. 

Project is due Friday at 10pm. My email is nicole.lewis@journalism.cuny.edu 

Thanks! 

My pitch: https://docs.google.com/a/journalism.cuny.edu/document/d/1lh7t_Xd7fycGghsVxqzmMms_izyw2iZz9vesBT0CtGE/edit?usp=sharing

**Comment by jueyang** [comment]
It's awesome you are exploring all the datasets you mentioned in your pitch, and that you are reasoning your choices. Also, kudos to you for inspecting elements!

After diving into BLS a bit myself (with the help of Google and non-help of the BLS database search), I find a few threads that might be of help.
1. Your logic makes a lot of sense. It is essentially the same as how BLS calculates total working hours in 2014: http://www.bls.gov/respondents/iif/totalhours.htm
2. BLS decided to use **hours at work**, as opposed to **hours paid**, to measure productivity. http://www.bls.gov/mlr/1990/02/art2full.pdf This methodology change came around 1990 (see publication date of the pdf), which makes me think that a 1964-2015 narrative might need to be broken up into smaller pieces (1990-2015 maybe?)
3. Google led me to a [book snippet](http://ase.tufts.edu/gdae/CS/Overworked.pdf) that brings up **Current Population Survey** by the BLS, which subsequently led me to the [data](http://www.bls.gov/cps/lfcharacteristics.htm#hours) of **persons at work by hours of work**. Although this only shows data for 2014, it at least means BLS keeps track of this particular measure.

Your hunch to break up the data into sectors is probably a more interesting angle. **Persons at work by hours of work** would probably not help much on the sector narrative. I would keep digging for datasets that include **persons at work by hours of work** and **by sector**.

Hope this helps. Join the [slack channel](chatwithjue.slack.com) with your email if you bump into more hurdles. The BLS site (and their methodologies) are not the most user-friendly!

**Comment by jueyang** [comment]
Hope that was helpful!
