### ISSUE TITLE
Setting up my website

### ISSUE THREAD

**Issue by EvWasLike** [jueyang/call-me-maybe#28]
Hi Jue Yang,

I have a web domain I bought via BlueHost, but am now having trouble figuring out next steps. I installed Wordpress, but cannot log into the wp-admin site. Also, when I tried to connect to my site's FTP server via Cyberduck, it gave me the following message:

> DNS lookup for ftp.evericwhite.com failed. DNS is the network service that translates a server name to its Internet address. This error is most often caused by having no connection to the Internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing access to the network.

I was wondering if you could help me set my site up. I plan on doing a portfolio that encompasses my clips, photography, projects I've worked on, social media profiles, and an about me section. How can I fix the original problem so that I can begin setting up my site?

Thank you!

**Comment by jueyang** [comment]
Hi @EvWasLike,

I'm no expert on WP issues. But you might want to start with googling "installing wordpress bluehost". Led me to this: https://my.bluehost.com/cgi/help/wp_install

You might find other people in the coach list who can help you with specific Wordpress problems. Thanks.
