### ISSUE TITLE
Help with google fusion and merging

### ISSUE THREAD

**Issue by emilysiegel** [jueyang/call-me-maybe#29]
Hi Jue,

I'm having trouble merging the US Zip codes to my google fusion chart. I went to file and then merge but it didn't seem to work. I'm not sure if this is the way to setup an appointment with you but please let me know if you're available at all today. Thanks!

**Comment by jueyang** [comment]
Hey Emily,

Please find my available times at https://calendly.com/jue/chat.

Not entirely sure about what you mean by "merging" here. It could be you have a problem in your dataset, or something else. Start with some googling: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=use+zipcode+for+google+fusion+chart

**Comment by jueyang** [comment]
Emily, I'm closing this issue now. If you still have questions, feel free to reopen it.
