### ISSUE TITLE
MAP HELP

### ISSUE THREAD

**Issue by danheching** [jueyang/call-me-maybe#30]
Hello,

I am completely lost in how to make a map for my interactive class. I have tried reaching out to other coaches to no avail. Let me know if you are available to help. Thank you!

**Comment by jueyang** [comment]
Hey,

Can you tell me what's bothering you? For example, do you have problem loading dataset? Are you having problems understanding the different types of visualizations, etc?

Without specific questions, I suggest you look into the well-documented CartoDB tutorials: http://docs.cartodb.com/tutorials.html

If you have more questions after perusing the tutorials, you can schedule something with me at calendly.com/jue/chat. But come in with specific questions!

Thanks.

**Comment by danheching** [comment]
Thanks for writing back. I wish I was even at the point of constructing the map. My question is more along the lines of culling data/research. I need to establish differences in population between two or three neighboring neighborhoods, but they all share the same zip code and same census tract. They are also both part of the same community board. What other ways can I search for population statistics? I don’t know if this is your specialty, but wanted to respond. 

Thank you
Dan Heching
Dan.heching@journalism.cuny.edu mailto:Dan.heching@journalism.cuny.edu 
CUNY J School / NY City News Service 
http://www.nycitynewsservice.com/ http://www.nycitynewsservice.com/

**Comment by jueyang** [comment]
Ask away! Most answers are there if you google them with precise terms. For example: search [population by neighborhood nyc](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=population%20by%20neighborhood%20nyc) and the first link might be what you are looking for.

When in doubt, google.

**Comment by jueyang** [comment]
Closing this. If you've got more questions, fire a new issue. Thanks!
