### ISSUE TITLE
Map Help 

### ISSUE THREAD

**Issue by pilarmarite** [jueyang/call-me-maybe#32]
Hi! I was wondering if you had anytime today to help me with a map I'm trying to create? I've found all the data I need on gyms. But I'm having trouble overlaying population density on my map.

**Comment by jueyang** [comment]
Can you tell me what the trouble is?

Here is a tutorial from CartoDB on creating a choropleth map of the US
population density.
http://academy.cartodb.com/courses/01-beginners-course/lesson-2.html

Make sure you have the data (the geometry and the numerical). For example,
if you are doing population density for community districts in NYC, you
would need a geojson or shapefile that has the community district boundary
as well as population per square meter (or something along that line).

If you still have question after reading the tutorial and trying it with
the right data, you may come with your question between 3-4:30pm today or
schedule something at calendly.com/chatwithjue

**Comment by pilarmarite** [comment]
Thank you for the information

**Comment by pilarmarite** [comment]
I'm still having some issues. I'm free until 4. Do you happen to be around?

**Comment by jueyang** [comment]
Can you tell me what issue it is in words? Document what you've done and
what's not working so that I can help you diagnose. I have a meeting that
is running late. You can find my schedule at the link above. Tomorrow 2-4pm
works as well.

**Comment by pilarmarite** [comment]
So, I was able to find population density data on cartodb, that I successfully merged and mapped. The problem is I can't see the source of this data. Before this I spent two hours trying to find and map the proper data (geojson), but with no luck. I'm about to try my data search again.

**Comment by jueyang** [comment]
By source, do you mean where the data comes from? That should be where you downloaded the data, eg. US Census.

Or do you mean something else? Send screenshots that might explain your troubles!
