### ISSUE TITLE
Excel Help

### ISSUE THREAD

**Issue by joshkeefe** [jueyang/call-me-maybe#33]
Hi! I am trying to analyze some data for a story due tomorrow night at midnight and I realize that I don't know Excel well enough (or at all) to do what I am trying to do. Can I come by sometime tomorrow and get some help? I actually think the solution is probably pretty simple, but long story short I don't understand pivot tables.

**Comment by jueyang** [comment]
Your short story might be solved by reading some tutorials. It's very general, so I can point you to one google query: "pivot table tutorials".  For example, this one is pretty clear, it walks you through the data, as well as the excel interface to re-organize that data: http://www.timeatlas.com/excel-pivot-tables/

The section on wikipedia gives a simple illustration regarding what pivot tables are: https://en.wikipedia.org/wiki/Pivot_table#Mechanics

If, after reading the tutorials, you still can't figure out what to do with the data, you can post what you have done with your data so far (what is it? what are you trying to achieve?), and post some screenshots explaining the problem you are running into. We can then schedule a time if needed.

I will be here to give you some guidance when you get stuck -- but you gotta become stuck in a specific problem first!
