### ISSUE TITLE
Version control class, from John Campbell

### ISSUE THREAD

**Issue by johnfcampbell** [jueyang/call-me-maybe#34]
My most recent data journalism project was part of Gannett's Changing Face of America series. I helped give the Courier-Post a more granular look at diversity in Southern New Jersey. USA Today provided a dataset, excerpted from census data, that showed diversity at the county level. I used IRE's bulk census, also owing to USA Today, to compute a diversity index for each of the 101 towns in the three-county circulation area. The figures mostly were a tool for reporter Kim Mulford to tell the story in narrative form. More on the project at: cpnewsroom.info/diversity

Earlier data projects similarly involved government data. We had an annual dive of education data provided by the state. The work was a grab-bag of Access, Excel and one-shot Perl scripts that have been lost to history. 

Aside from diversity, the repositories at github.com/johnfcampbell are largely devoted to work-flow tools, including shovelware. 

I have not really used Github to collaborate, only to document, if you want to call it that. You witnessed the one exception, Hack Jersey, and Github was apparently under attack that day. (Wound up using copy-paste, rather than a push).

**Comment by jueyang** [comment]
Thanks, John.
