### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by lmechegaray** [jueyang/call-me-maybe#4]
Hi Jue!
I am new to the Github world.....so apologies for my ignorance!
Is there an easy way to change the font of our texts?  I have gone far enough to use MARKDOWN....but if i want to, for example, use bold/italics or insert hyperlinks......

how do i do this?

Thanks so much for you help!

Luis M

**Comment by amandabee** [comment]
Check out the Markdown documentation: http://daringfireball.net/projects/markdown/dingus

**Comment by jueyang** [comment]
@lmechegaray Yeah. Check out what @amandabee suggested above. 

Or click the "Markdown supported" when you edit/comment on this issue. It's another overview of the markdown syntax. :eyes: 

![](http://cl.ly/image/290u3z2x2W1q/Screen%20Shot%202015-02-12%20at%2012.16.02%20AM.png)

**Comment by lmechegaray** [comment]
Great, thanks so much!
