### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by BetsyBagel** [jueyang/call-me-maybe#5]
Hi Jueyang,

You sat next to me in class today :)  I was wondering if you could email me about setting up an appointment to review some data skills if possible!

Thanks,
Betsy
betsy.laikin@journalism.cuny.edu

**Comment by jueyang** [comment]
Great! You should be getting a Slack invite in your email. We can discuss the specific skills to review once you sign in there.

PS. "You sat next to me in class" -- reminds me of the 90s. :notebook:

**Comment by jueyang** [comment]
@BetsyBagel good chatting with you yesterday. Let me know if you need anything else. Closing this one.
