### ISSUE TITLE
Help with CartoDB

### ISSUE THREAD

**Issue by KenAragaki** [jueyang/call-me-maybe#6]
Hi Jue,

I am working on an interactive map project with CartoDB and wondering if I could embed a video clip directly on the map (so that when you clip on a dot or location on the map, a video pops up). Here's a map I have right now: https://kenaragaki.cartodb.com/viz/27cbbf1e-b3b3-11e4-ad98-0e018d66dc29/map

Thanks!
Ken Aragaki

**Comment by jueyang** [comment]
Hey Ken,

Doesn't look like there's a way to do that within the cartodb interface. What you want is a custom tooltip when you click on the point/polygon (like in [this](https://www.mapbox.com/mapbox.js/example/v1.0.0/video/) example.) We can discuss how you can make that happen based on what tools/coding knowledge you have :)

Can you leave me an email so I can send you an invite to the slack chatroom?

**Comment by KenAragaki** [comment]
Sure, I don't have much coding knowledge. But, we can discuss that in private. Here's my e-mail: ken.aragaki@journalism.cuny.edu

Thanks!
Ken

**Comment by jueyang** [comment]
Great. Watch out for a slack invitation!

**Comment by jueyang** [comment]
Hi Ken,

If you create a simple page in a gist you can follow [this tutorial](http://docs.cartodb.com/tutorials/custom_interactivity.html) for videos. Before the tutorial there're a few prepping steps involved:
1. You create a column called videos.
2. For each row of data you associate a url to a video, such as a youtube iframe.
3. Create a simple index.html with [gist](https://gist.github.com/)

Let me know if any of these doesn't make sense. Holler back on Slack!

**Comment by KenAragaki** [comment]
Will try it. Thanks!
Ken
