### ISSUE TITLE
ACS Data - Queer Women

### ISSUE THREAD

**Issue by Emily-Goldblum** [jueyang/call-me-maybe#7]
Hi Jue!

I remember you mentioning last week that ACS might have some good sets of data to gather more information on queer women in the U.S. I've looked around on the Census website and I feel like I'm in a maze. Although I can see some working papers that have used ACS data, I can't seem to locate any data that could be of use. 
Any suggestions for me or would you be able to meet at some point to discuss?

Best,
Emily

**Comment by jueyang** [comment]
Google is your bff. I think I got to that dataset by searching the following. Click the first link :)

![](http://cl.ly/image/1U0H3e2r0G3P/Screen%20Shot%202015-02-17%20at%205.03.07%20PM.png)

**Comment by jueyang** [comment]
The census website is not optimal for navigating... Let's just say that.
